/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TripId = IDL.Nat64;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TripStats = IDL.Record({
  'tripCount' : IDL.Nat,
  'totalKilometers' : IDL.Float64,
});
export const Trip = IDL.Record({
  'id' : TripId,
  'destination' : IDL.Text,
  'kilometers' : IDL.Float64,
  'date' : IDL.Text,
  'purpose' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTrip' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [TripId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTrip' : IDL.Func([TripId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTripStats' : IDL.Func([], [TripStats], ['query']),
  'getTripsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Trip)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTrip' : IDL.Func([Trip], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TripId = IDL.Nat64;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TripStats = IDL.Record({
    'tripCount' : IDL.Nat,
    'totalKilometers' : IDL.Float64,
  });
  const Trip = IDL.Record({
    'id' : TripId,
    'destination' : IDL.Text,
    'kilometers' : IDL.Float64,
    'date' : IDL.Text,
    'purpose' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTrip' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [TripId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTrip' : IDL.Func([TripId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTripStats' : IDL.Func([], [TripStats], ['query']),
    'getTripsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Trip)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTrip' : IDL.Func([Trip], [], []),
  });
};

export const init = ({ IDL }) => { return []; };